// tests/regression/pricing-consistency.spec.js
//
// Does the same product cost the same amount everywhere it is quoted?
//
// The suite already checks pricing, but every existing check is self-consistent
// within ONE layer: pricing-api.spec.js reconciles best_price against its own
// competitors, emi-checkout-flow.spec.js reconciles the EMI ladder against its
// own price, product-pricing.spec.js checks one PDP shows a discount. None of
// them compares a figure on one surface against the same figure on another.
//
// So a product whose listing tile says ₹32,299, whose PDP says ₹36,999 and
// whose plan box says ₹34,000 passes the entire regression suite today. That is
// the gap this file closes: it walks the price ACROSS surfaces —
//
//     pricing API  ->  PLP tile  ->  PDP header  ->  PDP plan box (per plan)
//
// and asserts the shopper is shown one number, not three.
//
// The cart and Review Order legs live in pricing-checkout-consistency.spec.js,
// which needs a session. This file is entirely public and logged out: which
// plans exist and what they cost is product configuration, identical for every
// shopper, which CLAUDE.md names as the layer that is safe to assert. Nothing
// here touches per-shopper eligibility.

const { test, expect } = require('../fixtures/pageFixtures');
const { BASE_URL, TIMEOUTS } = require('../data/constants');
const { pdpApiPath, variantPricingPath } = require('../data/emiApi');
const { getWithRetry } = require('../utils/apiRetry');
const { parsePlpTile, parsePdpHeader, parsePlanBox, parseAddOn } = require('../utils/priceText');

// Logged out, deliberately and explicitly — same reason cardless-emi.spec.js and
// emi-plan-config.spec.js do it. It also makes every case here a candidate for
// the CI public list.
test.use({ storageState: { cookies: [], origins: [] } });

// A PDP renders in ~4s and the catalogue is ~200 products, so the sweeps below
// are slow by nature rather than by fault.
const CATALOGUE_TIMEOUT = 900000;
const PAGE_TIMEOUT = 120000;

// Instalments are whole rupees, so instalment x tenure can miss the exact total
// by up to one rupee per instalment. emi-checkout-flow.spec.js measured this:
// a 3-month plan on a ₹227,900 product legitimately totals ₹227,901. Anything
// beyond that allowance is a real charge, not rounding.
const roundingAllowance = (tenure) => tenure;

// Read the live listing rather than tests/data/products.json. That file was
// generated by an earlier `npm run discover` and holds 186 entries; the listing
// served 208 on 14 Aug 2026. Comparing a stale fixture against live prices would
// report catalogue drift as a pricing defect — the exact confusion CLAUDE.md
// warns about, since neither slug nor bpid is a stable key.
async function readListing(page) {
  await page.goto(`${BASE_URL}/all-products`, { waitUntil: 'domcontentloaded' });

  // Wait for the first tile before settling. scripts/discover-products.spec.js
  // settles on "the count stopped changing", which silently accepts zero: if no
  // tile has rendered yet the count is 0, it is 0 three rounds running, and the
  // loop exits reporting an empty catalogue. Measured — a re-run of this spec
  // logged "listing served 0 product tiles" and every sweep below then passed
  // vacuously or crashed. The floor has to be a real tile, not a stable number.
  await page
    .locator('a[href*="/pd/"]')
    .first()
    .waitFor({ state: 'visible', timeout: 30000 });

  // The listing lazy-loads, so now scroll until the count stops moving for
  // three consecutive rounds. `last > 0` is part of the exit condition for the
  // reason above.
  let last = 0;
  let stable = 0;
  while (stable < 3 || last === 0) {
    await page.mouse.wheel(0, 4000);
    await page.waitForTimeout(1200);
    const n = await page.locator('a[href*="/pd/"]').count();
    if (n === last && n > 0) stable++;
    else {
      stable = 0;
      last = n;
    }
  }

  const cards = page.locator('a[href*="/pd/"]');
  const total = await cards.count();
  const byHref = new Map();

  for (let i = 0; i < total; i++) {
    const card = cards.nth(i);
    const href = await card.getAttribute('href');
    if (!href || byHref.has(href)) continue;

    const match = /\/pd\/([^/?]+)\/([^/?]+)/.exec(href);
    if (!match) continue;

    const tile = parsePlpTile(await card.innerText().catch(() => ''));
    if (!tile) continue;

    byHref.set(href, { slug: match[1], bpid: match[2], href, tile });
  }

  return [...byHref.values()];
}

// by-slug -> variant id -> variant pricing. Two calls, because price is per
// variant and the listing links whichever variant is currently featured — which
// is not necessarily the master (CLAUDE.md).
async function pricingFor(request, { slug, bpid }) {
  const pdpRes = await getWithRetry(request, pdpApiPath(slug, bpid), {
    headers: { accept: 'application/json' },
  });
  if (!pdpRes.ok()) return { error: `by-slug ${pdpRes.status()}` };

  const pdp = await pdpRes.json();
  const variantId = pdp.data?.variant?.id;
  if (!variantId) return { error: 'by-slug returned no variant id' };

  const priceRes = await getWithRetry(request, variantPricingPath(slug, variantId), {
    headers: { accept: 'application/json' },
  });
  if (!priceRes.ok()) return { error: `variant-pricing ${priceRes.status()}` };

  const body = await priceRes.json();
  return {
    product: pdp.data.product,
    variant: pdp.data.variant,
    data: body.data || {},
  };
}

// Opens a PDP and waits for it to have actually priced itself.
//
// `domcontentloaded` plus a fixed sleep is not enough, and this was measured
// rather than assumed: at 3s, 2 of 8 sampled PDPs reported "no price in the
// header" while the same two parsed correctly on a clean load. The price is
// rendered after client-side hydration, so the wait has to be on the price
// itself. Anchored on the same locator ProductPage.priceText uses — the first
// node matching /^₹[\d,]+$/, which is the headline price in DOM order.
//
// Escape first: the site pops promo overlays over the PDP, and an overlay both
// covers the header and changes what innerText returns.
async function openPdp(page, { slug, bpid }) {
  await page.goto(`${BASE_URL}/pd/${slug}/${bpid}`, { waitUntil: 'domcontentloaded' });
  await page.keyboard.press('Escape').catch(() => {});

  await page
    .getByText(/^₹[\d,]+$/)
    .first()
    .waitFor({ state: 'visible', timeout: TIMEOUTS.nav });

  // The plan box arrives with the pricing round trip, a beat after the headline.
  await page
    .getByText(/choose your plan/i)
    .first()
    .waitFor({ state: 'visible', timeout: TIMEOUTS.nav })
    .catch(() => {});

  return page.locator('body').innerText();
}

// Run the catalogue sweep a few at a time. Serial takes ~15 minutes over 200
// products; unbounded parallelism rate-limits the origin, which is the same 429
// problem playwright.config.js caps workers for.
//
// Three, not five. At five the run completed but logged ~25 429s, several
// needing three backoff rounds — the retry helper absorbed them, which is
// exactly the situation playwright.config.js warns about: retries papering over
// contention until a real regression looks like the usual noise. Three keeps the
// sweep near two minutes with the origin quiet.
const BATCH = 3;

async function inBatches(items, size, worker) {
  const out = [];
  for (let i = 0; i < items.length; i += size) {
    out.push(...(await Promise.all(items.slice(i, i + size).map(worker))));
  }
  return out;
}

test.describe('Pricing consistency across surfaces', () => {
  let listing = [];

  // Scraped once and shared. Every case below reads the same listing, so a
  // re-scrape per test would triple the load on the origin for no benefit and
  // would let two cases disagree about what the catalogue contains.
  //
  // Throws rather than leaving `listing` empty: an empty list makes the sweeps
  // either crash on undefined or pass having checked nothing, and the second is
  // worse than a failure.
  test.beforeAll(async ({ browser }) => {
    const context = await browser.newContext({ storageState: { cookies: [], origins: [] } });
    const page = await context.newPage();
    try {
      listing = await readListing(page);
      console.log(`listing served ${listing.length} product tiles`);
      if (listing.length === 0) {
        throw new Error(
          'The listing page rendered no product tiles, so nothing below can be checked. ' +
            'This is a fixture failure, not a pricing result.'
        );
      }
    } finally {
      await context.close();
    }
  });

  // Non-vacuous guard. Every sweep below iterates `listing`, and an empty
  // listing would make all of them pass while asserting nothing — the failure
  // mode pricing-api.spec.js already guards against with its own fixture check.
  test('the listing rendered tiles to check', () => {
    expect(listing.length, '/all-products rendered no product tiles at all').toBeGreaterThan(20);

    const priced = listing.filter((entry) => entry.tile.price !== null);
    expect(
      priced.length,
      `${listing.length} tiles rendered but none of them carried a price`
    ).toBe(listing.length);
  });

  // ---- Surface 1 -> the API behind it ----------------------------------
  //
  // The whole catalogue, because a price glitch does not announce which product
  // it landed on, and a four-product sample is a coin flip. This is the widest
  // net in the file and the cheapest — no page loads, two API calls per product.
  test('every listing tile quotes the price its own pricing API returns', async ({ request }) => {
    test.setTimeout(CATALOGUE_TIMEOUT);

    const results = await inBatches(listing, BATCH, async (entry) => {
      const pricing = await pricingFor(request, entry);
      if (pricing.error) return { entry, unreachable: pricing.error };

      const upfront = pricing.data.upfront || {};
      const faults = [];

      if (entry.tile.price !== upfront.price) {
        faults.push(`tile shows ₹${entry.tile.price}, API upfront.price is ₹${upfront.price}`);
      }
      // Null means the tile carried no strike-through, which is correct for a
      // product with no discount. Only a tile that shows an MRP is held to it.
      if (entry.tile.mrp !== null && entry.tile.mrp !== upfront.cut_price) {
        faults.push(`tile MRP ₹${entry.tile.mrp}, API cut_price ₹${upfront.cut_price}`);
      }
      if (entry.tile.percentOff !== null && entry.tile.percentOff !== upfront.off_on_amount) {
        faults.push(
          `tile badge ${entry.tile.percentOff}% off, API off_on_amount ${upfront.off_on_amount}`
        );
      }
      // A discount badge with no saving behind it, or a saving with no badge.
      if (entry.tile.percentOff !== null && !(upfront.cut_price > upfront.price)) {
        faults.push(
          `tile advertises ${entry.tile.percentOff}% off but cut_price ₹${upfront.cut_price} ` +
            `is not above price ₹${upfront.price}`
        );
      }

      return { entry, faults };
    });

    const unreachable = results.filter((r) => r.unreachable);
    const mismatched = results.filter((r) => r.faults && r.faults.length);

    console.log(
      `checked ${results.length} tiles — ${mismatched.length} mismatched, ` +
        `${unreachable.length} unreachable`
    );

    // Unreachable is drift, not a pricing defect: slugs follow product names and
    // the listing links whichever variant is featured, so a 404 here means the
    // catalogue moved between the scrape and the call. Reported, not failed —
    // unless it is most of the catalogue, in which case the API is down and
    // every other result in this run is meaningless.
    if (unreachable.length) {
      console.log(
        'unreachable (catalogue drift):\n' +
          unreachable.map((r) => `  ${r.entry.slug}/${r.entry.bpid} — ${r.unreachable}`).join('\n')
      );
    }
    expect(
      unreachable.length,
      `${unreachable.length} of ${results.length} products could not be priced at all`
    ).toBeLessThan(results.length / 2);

    expect(
      mismatched.map((r) => `${r.entry.slug}: ${r.faults.join('; ')}`),
      'A listing tile is quoting a price the pricing API does not agree with. ' +
        'Whichever is right, a shopper is being shown a number that changes when they click.'
    ).toEqual([]);
  });

  // ---- Surface 1 -> Surface 2 ------------------------------------------
  //
  // The click. This is the hop a shopper makes and the one nothing covered.
  const HEADER_SAMPLE = 8;

  test('the PDP header repeats the listing tile, figure for figure', async ({ page, request }) => {
    test.setTimeout(CATALOGUE_TIMEOUT);

    // Spread across the catalogue rather than the first N, which are all one
    // brand — the sampling rule pricing-api.spec.js already uses.
    const step = Math.max(1, Math.floor(listing.length / HEADER_SAMPLE));
    const sample = listing.filter((_, i) => i % step === 0).slice(0, HEADER_SAMPLE);
    expect(sample.length, 'no products to sample').toBeGreaterThan(1);

    const faults = [];

    for (const entry of sample) {
      const header = parsePdpHeader(await openPdp(page, entry));
      if (!header) {
        faults.push(`${entry.slug}: the PDP rendered no price in its header at all`);
        continue;
      }

      const pricing = await pricingFor(request, entry);
      const upfront = pricing.error ? {} : pricing.data.upfront || {};

      if (header.price !== entry.tile.price) {
        faults.push(
          `${entry.slug}: tile ₹${entry.tile.price} -> PDP ₹${header.price}. ` +
            'The price changed when the shopper clicked through.'
        );
      }
      if (entry.tile.mrp !== null && header.mrp !== entry.tile.mrp) {
        faults.push(`${entry.slug}: tile MRP ₹${entry.tile.mrp} -> PDP MRP ₹${header.mrp}`);
      }
      if (entry.tile.percentOff !== null && header.percentOff !== entry.tile.percentOff) {
        faults.push(
          `${entry.slug}: tile ${entry.tile.percentOff}% off -> PDP ${header.percentOff}% off`
        );
      }
      // The monthly figure both surfaces advertise. The PLP labels it "EMI
      // from" and the PDP "Subscription from" on the same product, so only the
      // number is compared, not the copy.
      if (entry.tile.perMonth !== null && header.perMonth !== null) {
        if (header.perMonth !== entry.tile.perMonth) {
          faults.push(
            `${entry.slug}: tile ₹${entry.tile.perMonth}/mo -> PDP ₹${header.perMonth}/mo`
          );
        }
      }
      if (!pricing.error && header.price !== upfront.price) {
        faults.push(`${entry.slug}: PDP header ₹${header.price}, API ₹${upfront.price}`);
      }

      console.log(
        `${entry.slug}: tile ₹${entry.tile.price} = PDP ₹${header.price} = API ₹${upfront.price ?? '-'}`
      );
    }

    expect(faults, 'The price a shopper sees changed between the listing and the product page.')
      .toEqual([]);
  });

  // ---- Surface 2, plan by plan -----------------------------------------
  //
  // "All payment types" means every row the plan box offers. Which rows render
  // is driven by prodPaymentMode, so the two layouts are asserted separately.

  test('an upfront product prices every plan it offers the way the API does', async ({
    page,
    request,
  }) => {
    test.setTimeout(PAGE_TIMEOUT);

    const candidate = listing.find((e) => e.tile.perMonth === null) || listing[0];
    const pricing = await pricingFor(request, candidate);
    expect(pricing.error, `could not price ${candidate.slug}`).toBeFalsy();
    test.skip(
      pricing.product.prodPaymentMode !== 'UPFRONT',
      `${candidate.slug} is ${pricing.product.prodPaymentMode}, not UPFRONT`
    );

    const box = parsePlanBox(await openPdp(page, candidate));
    expect(box, `${candidate.slug} rendered no "Choose your plan" box`).toBeTruthy();
    console.log(`${candidate.slug} plans: ${box.plans.join(', ')}`);

    const upfront = pricing.data.upfront || {};
    const options = pricing.data.emi?.emi_option || [];
    const faults = [];

    // Pay in Full — the plan every product offers.
    expect(box.payInFull, `${candidate.slug} offers no "Pay in Full" price`).toBeTruthy();
    if (box.payInFull !== upfront.price) {
      faults.push(`Pay in Full shows ₹${box.payInFull}, API upfront.price is ₹${upfront.price}`);
    }

    // The EMI rungs the box quotes must be rungs the API actually offers. The
    // box renders a subset — a "Recommended" NCEMI rung and the longest LCEMI
    // rung — so this asserts membership, not equality with the full ladder.
    expect(
      box.tenureRows.length,
      `${candidate.slug} advertises EMI but quotes no "₹X x N mo" figure`
    ).toBeGreaterThan(0);

    for (const row of box.tenureRows) {
      const match = options.find((o) => o.tenure === row.tenure);
      if (!match) {
        faults.push(
          `the box offers ₹${row.installment} x ${row.tenure}mo but the API ladder has no ` +
            `${row.tenure}-month option (it has ${options.map((o) => o.tenure).join(', ')})`
        );
        continue;
      }
      if (match.installment_amount !== row.installment) {
        faults.push(
          `the box quotes ₹${row.installment}/mo for ${row.tenure}mo, the API says ` +
            `₹${match.installment_amount}`
        );
      }
    }

    // "Instant Discount of ₹1500" is the figure the API calls instant_discount,
    // and CLAUDE.md is explicit that it is already inside MOP — so MRP must sit
    // at least that far above the price, or the saving is promised twice.
    if (box.instantDiscount !== null) {
      if (box.instantDiscount !== upfront.instant_discount) {
        faults.push(
          `box says Instant Discount ₹${box.instantDiscount}, API instant_discount is ` +
            `₹${upfront.instant_discount}`
        );
      }
      if (upfront.cut_price - upfront.price < box.instantDiscount) {
        faults.push(
          `an instant discount of ₹${box.instantDiscount} is claimed, but MRP ₹${upfront.cut_price} ` +
            `is only ₹${upfront.cut_price - upfront.price} above the price`
        );
      }
    }

    expect(faults, `${candidate.slug}: the plan box and the pricing API disagree`).toEqual([]);
  });

  test('a subscription product prices every plan it offers the way the API does', async ({
    page,
    request,
  }) => {
    test.setTimeout(PAGE_TIMEOUT);

    // Find a BOTH-mode product from the live listing rather than a pinned slug,
    // which drifts. The subscription layout is the one that renders Buy Upfront,
    // Cardless EMI, Pre-Approved Offers and Monthly Subscription together, so it
    // is where "all payment types" is actually assertable in one place.
    let subject = null;
    for (const entry of listing.filter((e) => e.tile.perMonth !== null).slice(0, 12)) {
      const pricing = await pricingFor(request, entry);
      if (!pricing.error && pricing.product.prodPaymentMode === 'BOTH') {
        subject = { entry, pricing };
        break;
      }
    }
    test.skip(!subject, 'no BOTH-mode product found in the listing sample');

    const { entry, pricing } = subject;
    const box = parsePlanBox(await openPdp(page, entry));
    expect(box, `${entry.slug} rendered no "Choose your plan" box`).toBeTruthy();
    console.log(`${entry.slug} plans: ${box.plans.join(', ')}`);

    const { upfront = {}, cc = {}, nbfc = {} } = pricing.data;
    const faults = [];

    // Plan: Buy Upfront.
    expect(box.buyUpfront, `${entry.slug} offers no "Buy Upfront" price`).toBeTruthy();
    if (box.buyUpfront !== upfront.price) {
      faults.push(`Buy Upfront shows ₹${box.buyUpfront}, API upfront.price is ₹${upfront.price}`);
    }

    // Plan: Credit Card EMI — data.cc.
    if (box.creditCardEmiPerMonth !== null && box.creditCardEmiPerMonth !== cc.emi_amount) {
      faults.push(
        `Credit Card EMI shows ₹${box.creditCardEmiPerMonth}/mo, API cc.emi_amount is ₹${cc.emi_amount}`
      );
    }

    // Plan: Monthly Subscription — the same cc figure, under a different name.
    if (box.monthlySubscription !== null && box.monthlySubscription !== cc.emi_amount) {
      faults.push(
        `Monthly Subscription shows ₹${box.monthlySubscription}/mo, API cc.emi_amount is ₹${cc.emi_amount}`
      );
    }

    // Plan: Cardless EMI — data.nbfc. CLAUDE.md: nbfc is the pre-computed
    // cardless figure for the SUBSCRIPTION plan, and an emi_amount of 0 means
    // "not pre-priced" rather than "unavailable". So the figures are only held
    // to the API where the API actually published one. Eligibility — the
    // Pre-approved badge, the "not eligible" line — is never asserted; it is
    // per shopper and changes between page loads.
    if (box.cardlessEmiPerMonth !== null) {
      if (!nbfc.emi_amount) {
        faults.push(
          `the box quotes Cardless EMI at ₹${box.cardlessEmiPerMonth}/mo but the API published ` +
            `no nbfc.emi_amount (${nbfc.emi_amount}) to substantiate it`
        );
      } else if (box.cardlessEmiPerMonth !== nbfc.emi_amount) {
        faults.push(
          `Cardless EMI shows ₹${box.cardlessEmiPerMonth}/mo, API nbfc.emi_amount is ₹${nbfc.emi_amount}`
        );
      }
    }
    if (box.cardlessDownPayment !== null && nbfc.downpay && box.cardlessDownPayment !== nbfc.downpay) {
      faults.push(
        `Cardless EMI asks for ₹${box.cardlessDownPayment} now, API nbfc.downpay is ₹${nbfc.downpay}`
      );
    }

    // Plan: Pre-Approved Offers. A separate plan with its own eligibility, NOT
    // cardless EMI (CLAUDE.md). Whatever it quotes must still be a real figure
    // the API published — it currently mirrors the card-EMI instalment.
    if (box.preApprovedFrom !== null) {
      const known = [cc.emi_amount, nbfc.emi_amount].filter(Boolean);
      if (known.length && !known.includes(box.preApprovedFrom)) {
        faults.push(
          `Pre-Approved Offers quotes ₹${box.preApprovedFrom}/mo, which matches neither ` +
            `cc.emi_amount ₹${cc.emi_amount} nor nbfc.emi_amount ₹${nbfc.emi_amount}`
        );
      }
    }

    console.log(
      `${entry.slug}: upfront ₹${box.buyUpfront} · cc ₹${box.creditCardEmiPerMonth}/mo · ` +
        `cardless ₹${box.cardlessEmiPerMonth}/mo + ₹${box.cardlessDownPayment} · ` +
        `sub ₹${box.monthlySubscription}/mo`
    );

    expect(faults, `${entry.slug}: the plan box and the pricing API disagree`).toEqual([]);
  });

  // ---- The advertised saving --------------------------------------------
  //
  // "🎉 You'll save up to ₹27,307" and "Total Discount ₹27,307" are the largest
  // numbers on the page and the ones a shopper is most likely to act on. They
  // must be the same figure as each other, and they must not exceed the most
  // anyone could actually save.
  test('the advertised saving is internally consistent and not larger than any real saving', async ({
    page,
    request,
  }) => {
    test.setTimeout(PAGE_TIMEOUT);

    let subject = null;
    for (const entry of listing.filter((e) => e.tile.perMonth !== null).slice(0, 12)) {
      const pricing = await pricingFor(request, entry);
      if (!pricing.error && pricing.product.prodPaymentMode === 'BOTH') {
        subject = { entry, pricing };
        break;
      }
    }
    test.skip(!subject, 'no BOTH-mode product found in the listing sample');

    const { entry, pricing } = subject;
    const body = await openPdp(page, entry);
    const box = parsePlanBox(body);
    const addOn = parseAddOn(body);
    const { upfront = {}, cc = {} } = pricing.data;

    test.skip(box.saveUpTo === null, `${entry.slug} advertises no saving`);

    // The banner and the breakdown line are two renderings of one figure.
    if (box.totalDiscount !== null) {
      expect(
        box.saveUpTo,
        `${entry.slug}: the banner says save up to ₹${box.saveUpTo} but the breakdown line ` +
          `says Total Discount ₹${box.totalDiscount}. Same page, two numbers.`
      ).toBe(box.totalDiscount);
    }

    // The claim, reconciled to the rupee rather than bounded.
    //
    //   Total Discount = (MRP - cc.total_amount) + (add-on list - add-on paid)
    //
    // Derived by measurement, not assumption, and confirmed exact on both
    // subscription products available on 14 Aug 2026:
    //
    //   Galaxy Z Fold8 Ultra  204999 - 183693 = 21306  + (8000 - 1999) = 27307
    //   Macbook Pro M5        239900 - 217632 = 22268  + (8000 -    1) = 30267
    //
    // Both are exactly what the PDP prints. The add-on term is the one a bounds
    // check would have to give up on — and it is 22% of the headline saving on
    // the Fold8, so giving up on it means the largest number on the page goes
    // unchecked.
    const mrp = upfront.cut_price ?? upfront.mop_base;
    const deviceSaving = mrp - cc.total_amount;
    const addOnSaving = addOn ? addOn.saving : 0;

    console.log(
      `${entry.slug}: advertised ₹${box.saveUpTo} = device ₹${deviceSaving} ` +
        `(MRP ₹${mrp} - cc.total ₹${cc.total_amount})` +
        (addOn ? ` + ${addOn.name} ₹${addOn.list}->₹${addOn.paid} = ₹${addOnSaving}` : ' + no add-on')
    );

    expect(
      box.saveUpTo,
      `${entry.slug}: the PDP advertises a saving of ₹${box.saveUpTo}, but the figures behind ` +
        'it come to something else.\n' +
        `  MRP                      ₹${mrp}\n` +
        `  cheapest plan total     -₹${cc.total_amount}  (cc.total_amount)\n` +
        `  device saving            ₹${deviceSaving}\n` +
        `  ${addOn ? `${addOn.name} ₹${addOn.list} -> ₹${addOn.paid}` : 'no add-on line found'}` +
        `  +₹${addOnSaving}\n` +
        `  expected                 ₹${deviceSaving + addOnSaving}\n` +
        `  advertised               ₹${box.saveUpTo}\n` +
        'If the gap matches a bundled item this parser does not read, the page grew ' +
        'a second add-on. Otherwise the largest number on the page is overstated.'
    ).toBe(deviceSaving + addOnSaving);
  });

  // ---- Every rung, every product ---------------------------------------
  //
  // emi-checkout-flow.spec.js reconciles the EMI ladder for four products, from
  // a fixture file (cardless-emi.json) that was generated on an earlier run.
  // This does it for the whole live catalogue: a mispriced instalment on
  // product 130 is invisible to a four-product sample.
  test('every EMI tenure on offer, catalogue-wide, reconciles with its own price', async ({
    request,
  }) => {
    test.setTimeout(CATALOGUE_TIMEOUT);

    const results = await inBatches(listing, BATCH, async (entry) => {
      const pricing = await pricingFor(request, entry);
      if (pricing.error) return null;

      const options = pricing.data.emi?.emi_option || [];
      const price = pricing.data.upfront?.price;
      if (!options.length || !price) return null;

      const faults = [];

      for (const o of options) {
        // The formula emi-checkout-flow.spec.js measured exact on 6 of 6
        // tenures: instalment x tenure === price - discount + interest. NOT
        // (price + interest) / tenure, which omits the discount term and
        // matched 0 of 6.
        const charged = o.installment_amount * o.tenure;
        const expected = price - o.discount + o.interest;
        if (Math.abs(charged - expected) > roundingAllowance(o.tenure)) {
          faults.push(
            `${o.tenure}mo ${o.emi_type}: ${o.installment_amount} x ${o.tenure} = ${charged}, ` +
              `but price ${price} - discount ${o.discount} + interest ${o.interest} = ${expected}`
          );
        }

        // A No Cost EMI that costs more than paying upfront is a contradiction
        // in the plan's own name.
        if (o.emi_type === 'NCEMI' && charged - price > roundingAllowance(o.tenure)) {
          faults.push(
            `${o.tenure}mo No Cost EMI totals ${charged} on a ₹${price} product — ` +
              `₹${charged - price} more than rounding explains`
          );
        }

        if (!(o.installment_amount > 0) || !(o.tenure > 0)) {
          faults.push(`a ${o.tenure}-month option is offered at ${o.installment_amount}/mo`);
        }
      }

      // A ladder must behave like one: longer tenure, lower instalment, more
      // interest. Compared on interest rather than instalment x tenure, which
      // is whole-rupee rounded and reports rounding as a pricing fault.
      const sorted = [...options].sort((a, b) => a.tenure - b.tenure);
      for (let i = 1; i < sorted.length; i++) {
        if (sorted[i].installment_amount > sorted[i - 1].installment_amount) {
          faults.push(
            `${sorted[i].tenure}mo costs ${sorted[i].installment_amount}/mo, more than ` +
              `${sorted[i - 1].tenure}mo at ${sorted[i - 1].installment_amount}/mo`
          );
        }
        if (sorted[i].interest < sorted[i - 1].interest) {
          faults.push(
            `${sorted[i].tenure}mo charges ${sorted[i].interest} interest, less than ` +
              `${sorted[i - 1].tenure}mo at ${sorted[i - 1].interest}`
          );
        }
      }

      const tenures = options.map((o) => o.tenure);
      if (new Set(tenures).size !== tenures.length) {
        faults.push(`duplicate tenures offered: ${tenures.join(', ')}`);
      }

      return faults.length ? `${entry.slug}: ${faults.join(' | ')}` : null;
    });

    const broken = results.filter(Boolean);
    console.log(`EMI ladders checked across ${listing.length} products — ${broken.length} broken`);

    expect(
      broken,
      'An EMI plan quotes instalments that do not reconcile with the product price. ' +
        'A shopper on one of these tenures is charged something other than the ' +
        'advertised price plus interest.'
    ).toEqual([]);
  });
});
